# Generated by Django 3.2.16 on 2024-10-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Заголовок', max_length=50)),
                ('description', models.CharField(default='описание', max_length=1000)),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='зарпалата')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='длительность в месяцах')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/%Y/%m/%d', verbose_name='фотография')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
