# Generated by Django 3.2.16 on 2024-10-25 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_auto_20241017_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='echovacancy',
            options={'ordering': ['time_created', 'id'], 'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-time_created', 'id'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
