# Generated by Django 3.2.16 on 2024-11-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_vacancy_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='hours_per_week',
            field=models.IntegerField(default=40, verbose_name='занятость в неделю в часах'),
        ),
    ]
