# Generated by Django 3.2.16 on 2024-10-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Скилл', 'verbose_name_plural': 'Скиллы'},
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='user',
            new_name='intern',
        ),
    ]
