# Generated by Django 3.2.16 on 2024-10-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_intern_inn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='inn',
        ),
        migrations.AddField(
            model_name='employer',
            name='inn',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ИНН'),
        ),
    ]
