# Generated by Django 3.2.16 on 2024-11-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_employer_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='resume_link',
            field=models.TextField(blank=True, null=True, verbose_name='ссылка на резюме'),
        ),
    ]
